### ISSUE TITLE
[Feature Request] Disable links option

### ISSUE THREAD

**Issue by pilotkid** [eidam/cf-workers-status-page#54]
Hello, let's say that you want to have a status page that is open to the public, that shows the status of your front end and your backend. However, you do not want to openly publish your API server's URL. As of now, you have no control as to who can see/click on the URL of the server. I propose adding a setting to the `config.yml` file to allow the link to become disabled on the home page. 

For example, a configuration file would look like this

```yml
monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true #default=true
    
  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: false
```

Which in turn produces this result
![image](https://user-images.githubusercontent.com/6385285/126671278-e56b9c9c-ed11-4e5e-8ab4-a0cb53b4400a.png)
